name: Build and publish packages
on:
  push:
    branches: ['main']
jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: '5.x'
      - name: Determine version
        uses: gittools/actions/gitversion/execute@v0.9.9
        with:
          updateAssemblyInfo: true
      - name: Build packages
        run: dotnet pack -c Release -o ".packages"
      - name: Publish packages
        run: dotnet nuget push ".packages/*.nupkg" --api-key "${{secrets.GITHUB_TOKEN}}" --source "https://nuget.pkg.github.com/TechInterMezzo/index.json"