name: Build and publish packages
on:
  push:
    branches: ['main']
jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Build packages
        run: dotnet pack -c Release -o ".packages"
      - name: Publish packages
        run: dotnet nuget push ".packages/*.nupkg" --api-key ${{secrets.GITHUB_TOKEN}} --source "github"